services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"  # Host:Container
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: ac_dental
      MYSQL_USER: dental_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:     